#!/bin/bash
# QUICK START - Self-Healing Network System
# Copy & paste these commands to get running in 2 minutes

echo "🚀 QUICK START - Self-Healing Network System"
echo "============================================"
echo ""
echo "📦 TERMINAL 1 - Frontend (Vite Dev Server)"
echo "---"
echo "cd /path/to/HACKINTYM2K26-main"
echo "npm run dev"
echo "# Opens at http://localhost:8081"
echo ""
echo "📦 TERMINAL 2 - Backend (NestJS)"
echo "---"
echo "cd /path/to/HACKINTYM2K26-main/backend"
echo "npm run start:dev"
echo "# Backend at http://localhost:3001"
echo "# Swagger Docs: http://localhost:3001/api/docs"
echo ""
echo "🌐 STEP 3 - Open Dashboard"
echo "---"
echo "http://localhost:8081/network-healing"
echo ""
echo "✅ What you'll see:"
echo "  ✓ 100 nodes in 3D (green=healthy, red=failed, orange=overloaded)"
echo "  ✓ Real-time metrics (latency, traffic, health)"
echo "  ✓ Control buttons (Play/Stop/Reset)"
echo "  ✓ Failure event log with rerouting details"
echo ""
echo "🎮 Try these:"
echo "  1. Click [Start Simulation]"
echo "  2. Watch nodes change colors as load increases"
echo "  3. Click on a node to manually trigger failure"
echo "  4. See automatic rerouting happen in logs"
echo "  5. Watch node recovery in real-time"
echo ""
echo "============================================"
echo "📊 API Examples:"
echo ""
echo "Get network state:"
echo "  curl http://localhost:3001/api/network-healing/state | jq"
echo ""
echo "Get metrics:"
echo "  curl http://localhost:3001/api/network-healing/metrics | jq"
echo ""
echo "Start simulation:"
echo "  curl -X POST http://localhost:3001/api/network-healing/start"
echo ""
echo "Trigger failure:"
echo "  curl -X POST http://localhost:3001/api/network-healing/trigger-failure \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"nodeId\":\"node-42\"}'"
echo ""
echo "============================================"
echo "📚 Full documentation: NETWORK_HEALING_COMPLETE_GUIDE.md"
echo "🐛 Issues? Check http://localhost:3001/api/network-healing/metrics"
